"""Create job table

Revision ID: fcc00ea1db2d
Revises: 
Create Date: 2024-09-01 15:47:22.829554

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fcc00ea1db2d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('location', sa.String(length=100), nullable=False),
    sa.Column('salary', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('engineers')
    op.drop_table('jobs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=250), nullable=False),
    sa.Column('salary', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('currency', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('responsibilities', mysql.VARCHAR(length=2000), nullable=True),
    sa.Column('requirements', mysql.VARCHAR(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('engineers',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('specialization', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('experience_years', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('phone_number', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('linkedin_profile', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('portfolio_link', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('location', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('job')
    # ### end Alembic commands ###
